package handlers

const headerAccessControlAllowOrigin = "Access-Control-Allow-Origin"
const headerAccessControlAllowMethods = "Access-Control-Allow-Methods"
const headerAccessControlAllowHeaders = "Access-Control-Allow-Headers"
const headerAccessControlExposeHeaders = "Access-Control-Expose-Headers"
const headerAccessControlMaxAge = "Access-Control-Max-Age"
const allowHeadersAuth = "Content-Type, Authorization"
const exposeHeadersAuth = "Authorization"
const originAny = "*"
const maxAge = "600"
const headerContentType = "Content-Type"
const contentTypeJSON = "application/json"
const contentTypeHTML = "text/html"
const contentTypeText = "text/plain"
const headerRetryAfter = "Retry-After"
const headerForwardedFor = "X-Forwarded-For"
